### ISSUE TITLE
How work with images path

### ISSUE THREAD

**Issue by jonaxd1** [webOS-TV-app-samples/BackButtonControl#1]
How can I work with the image path through navigation? Because when you push a new page the location.href change to "file:///page1" when originally was "file:///Users/xxx/yyy/zzz/tests/first-app-testing/index.html" and the error "file:///icons/pause.png net::ERR_FILE_NOT_FOUND" appears. 

I joined this project with [MediaPlayback](https://github.com/webOS-TV-app-samples/MediaPlayback) project.

I'm testing on WebOS TV 22 Simulator.

Thank you.

**Comment by ghost** [comment]
Hi @jonaxd1 

If you referenced this sample, you would have used `<a ...... href='/page1'>`.
This seems to be a problem because it is recognized as an absolute path.
Could you check by changing the relative path?
`<a ...... href='./page1'>` or `<a ...... href='page1'>`.

**Comment by jonaxd1** [comment]
Using ```<a ...... href='./page1'>``` works great! Thank you for your support.
